modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: "ip4"
      valid_status_codes: [200, 201, 202, 203, 204, 205, 206, 207, 208, 226]
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: true
      headers:
        User-Agent: "Prometheus/Blackbox Exporter"
        Accept: "*/*"

  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      method: POST
      preferred_ip_protocol: "ip4"
      valid_status_codes: [200, 201, 202, 203, 204, 205, 206, 207, 208, 226]
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: true
      headers:
        User-Agent: "Prometheus/Blackbox Exporter"
        Content-Type: "application/json"
        Accept: "*/*"
      body: '{"test": "health_check"}'

  tcp_connect:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"
      tls: false
      tls_config:
        insecure_skip_verify: true

  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"

  dns:
    prober: dns
    timeout: 5s
    dns:
      preferred_ip_protocol: "ip4"
      query_name: "devopspilot.com"
      query_type: "A"
      valid_rcodes: [NOERROR]
      fail_if_rcode_not_matches: [NOERROR]
      fail_if_matches_regexp:
        - ".*\\.cloudflare\\.com$"
        - ".*\\.cloudflare\\.net$"
      fail_if_not_matches_regexp:
        - ".*\\.devopspilot\\.com$"

  grpc:
    prober: grpc
    timeout: 5s
    grpc:
      preferred_ip_protocol: "ip4"
      tls: false
      tls_config:
        insecure_skip_verify: true
      service: "grpc.health.v1.Health"
